### ISSUE TITLE
Not helpful default configuration

### ISSUE THREAD

**Issue by eliska-n** [TeskaLabs/asab-iris#11]
https://github.com/TeskaLabs/asab-iris/blob/0cb7de6ba2b19f5fca5bb8ef61b44e0baaf926b6/asabiris/output/smtp/service.py#L20

If `from` is missing (empty string), sendgrid accepts the requests, returns 200, but never sends the e-mail. If `from` is not configured, I'm losing e-mails in the SMTP server without any warning. I know this might be sendgrid-specific, but it would be great if the default configuration were functional (when present) or the `from` item was required in the input/handler/json_schema.

**Comment by ateska** [comment]
Closed by #10
