### ISSUE TITLE
Sending SMS

### ISSUE THREAD

**Issue by byewokko** [TeskaLabs/asab-iris#3]
- [ ] Support SMSbrána.cz ([see the respective TeskaLabs/seacat-auth module for reference](https://github.com/TeskaLabs/seacat-auth/blob/main/seacatauth/communication/sms_smsbranacz.py))

**Comment by byewokko** [comment]
@ateska is this really closed as "completed"? the corresponding pull request #6 is still open.

**Comment by ateska** [comment]
it is not productive to keep this issue open.
